version: "3.7"
services:
  proffy-web:
    container_name: proffy-web
    build: web/
    ports:
      - 1337:80
    depends_on:
      - proffy-api
  proffy-api:
    build: server/
    ports:
      - 8081:8081